"""
afeez — Jupyter (R kernel) notebook builder.

Fill in the CONFIG block, then run:
    python3 build_afeez_notebook.py

Produces: afeez_eda.ipynb in the current directory.
"""

import json
from pathlib import Path

# =========================================================================
# CONFIG — fill these in from the user's answers
# =========================================================================
DATA_PATH   = "data/nhanes.csv"
OUTCOME     = "Diabetes"
SEL_VARS    = ["Age", "Gender", "Race1", "Weight", "Height", "Diabetes", "BPSysAve", "BPDiaAve"]
FILTER_EXPR = "Age >= 18 & Age <= 50"
PLOTS_DIR   = "plots"
TABLE_PATH  = "bivariate_table.html"
OUT_PATH    = "afeez_eda.ipynb"
# =========================================================================


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": _src(lines),
        "outputs": [],
    }


def _src(lines):
    # Join into a list of lines with \n at the end of each except the last —
    # the .ipynb v4 schema accepts either a string or a list of strings.
    text = "\n".join(lines)
    parts = text.split("\n")
    return [p + ("\n" if i < len(parts) - 1 else "") for i, p in enumerate(parts)]


# R literal helpers
def r_str(s):
    return "NULL" if s is None else '"' + str(s).replace('"', '\\"') + '"'


def r_char_vec(xs):
    if xs is None:
        return "NULL"
    return "c(" + ", ".join(r_str(x) for x in xs) + ")"


def r_filter_expr(expr):
    # expr is either None or a raw R expression string usable inside filter(...)
    return "NULL" if expr is None else expr


sel_vars_r    = r_char_vec(SEL_VARS)
filter_expr_r = r_filter_expr(FILTER_EXPR)
data_path_r   = r_str(DATA_PATH)
outcome_r     = r_str(OUTCOME)
plots_dir_r   = r_str(PLOTS_DIR)
table_path_r  = r_str(TABLE_PATH)

vars_line   = "all columns" if SEL_VARS is None else ", ".join(SEL_VARS)
filter_line = "none" if FILTER_EXPR is None else f"`{FILTER_EXPR}`"

cells = []

# ---- 1. Title -----------------------------------------------------------
cells.append(md(
    "# afeez EDA report",
    "",
    f"- **Data**: `{DATA_PATH}`",
    f"- **Outcome**: `{OUTCOME}`",
    f"- **Variables**: {vars_line}",
    f"- **Filter**: {filter_line}",
    "",
    "Generated by the `afeez` skill.",
))

# ---- 2. Libraries -------------------------------------------------------
cells.append(md("## 1. Libraries"))
cells.append(code(
    "library(tidyverse)",
    "library(gtsummary)",
    "library(gt)",
    "library(skimr)",
))

# ---- 3. Load & prep -----------------------------------------------------
cells.append(md("## 2. Load and prepare data"))
cells.append(code(
    f"data_path   <- {data_path_r}",
    f"outcome     <- {outcome_r}",
    f"sel_vars    <- {sel_vars_r}",
    f"plots_dir   <- {plots_dir_r}",
    f"table_path  <- {table_path_r}",
    "",
    "df <- readr::read_csv(data_path, na = c(\"\", \"NA\", \"N/A\", \".\"))",
    "",
    "if (!is.null(sel_vars)) df <- df %>% select(all_of(sel_vars))",
    "",
    f"# User-supplied filter (or no-op)",
    f"df <- df %>% filter({filter_expr_r if FILTER_EXPR else 'TRUE'})",
    "",
    "# Drop rows where outcome is missing; coerce outcome to factor",
    "df <- df %>% filter(!is.na(.data[[outcome]]))",
    "df[[outcome]] <- factor(df[[outcome]])",
    "",
    "# Coerce character columns to factor",
    "chr_cols <- names(df)[sapply(df, is.character)]",
    "for (v in chr_cols) df[[v]] <- factor(df[[v]])",
    "",
    "dir.create(plots_dir, recursive = TRUE, showWarnings = FALSE)",
    "",
    "cat(\"Rows:\", nrow(df), \"  Cols:\", ncol(df), \"\\n\")",
    "cat(\"Outcome levels:\\n\"); print(table(df[[outcome]]))",
))

# ---- 4. Overview --------------------------------------------------------
cells.append(md("## 3. Dataset overview"))
cells.append(code("glimpse(df)"))
cells.append(code(
    "df %>%",
    "  summarise(across(everything(), ~ sum(is.na(.)))) %>%",
    "  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_missing\") %>%",
    "  mutate(pct_missing = round(100 * n_missing / nrow(df), 1)) %>%",
    "  arrange(desc(n_missing))",
))
cells.append(code("skim(df)"))

# ---- 5. Normality -------------------------------------------------------
cells.append(md("## 4. Normality (Shapiro–Wilk) for numeric predictors"))
cells.append(code(
    "num_vars <- setdiff(names(df)[sapply(df, is.numeric)], outcome)",
    "cat_vars <- setdiff(names(df)[sapply(df, function(x) is.factor(x) || is.character(x))], outcome)",
    "",
    "is_normal <- function(x) {",
    "  vals <- na.omit(x)",
    "  n <- length(vals)",
    "  if (n >= 3 && n <= 5000) stats::shapiro.test(vals)$p.value > 0.05 else FALSE",
    "}",
    "normality <- tibble::tibble(",
    "  variable = num_vars,",
    "  is_normal = vapply(num_vars, function(v) is_normal(df[[v]]), logical(1))",
    ")",
    "normality",
))

# ---- 6. Univariate plots ------------------------------------------------
cells.append(md("## 5. Univariate plots",
                "",
                "Numeric: histogram + boxplot. Categorical: bar chart with count and percent labels.",
                "All plots use `theme_minimal()` and are saved to `plots_dir`."))
cells.append(code(
    "for (v in num_vars) {",
    "  p_hist <- ggplot(df, aes(x = .data[[v]])) +",
    "    geom_histogram(bins = 30, fill = \"steelblue\", color = \"white\", alpha = 0.8) +",
    "    theme_minimal() +",
    "    labs(title = paste(\"Distribution of\", v), x = v, y = \"Count\")",
    "  print(p_hist)",
    "  ggsave(file.path(plots_dir, paste0(\"uni_hist_\", v, \".png\")), p_hist,",
    "         width = 6, height = 4, dpi = 150)",
    "",
    "  p_box <- ggplot(df, aes(y = .data[[v]])) +",
    "    geom_boxplot(fill = \"steelblue\", alpha = 0.6, outlier.color = \"red\") +",
    "    theme_minimal() +",
    "    labs(title = paste(\"Boxplot of\", v), x = \"\", y = v)",
    "  print(p_box)",
    "  ggsave(file.path(plots_dir, paste0(\"uni_box_\", v, \".png\")), p_box,",
    "         width = 6, height = 4, dpi = 150)",
    "}",
))
cells.append(code(
    "for (v in cat_vars) {",
    "  p_bar <- df %>%",
    "    count(.data[[v]]) %>%",
    "    mutate(pct = scales::percent(n / sum(n), accuracy = 0.1)) %>%",
    "    ggplot(aes(x = .data[[v]], y = n, fill = .data[[v]])) +",
    "    geom_col(show.legend = FALSE) +",
    "    geom_text(aes(label = paste0(n, \" (\", pct, \")\")), vjust = -0.3, size = 3) +",
    "    theme_minimal() +",
    "    labs(title = paste(\"Distribution of\", v), x = v, y = \"Count\")",
    "  print(p_bar)",
    "  ggsave(file.path(plots_dir, paste0(\"uni_bar_\", v, \".png\")), p_bar,",
    "         width = 6, height = 4, dpi = 150)",
    "}",
))

# ---- 7. Bivariate gtsummary table --------------------------------------
cells.append(md(
    "## 6. Bivariate gtsummary table",
    "",
    "Includes **Overall** column, one column per outcome level, and **p-values**.",
    "",
    "- Normal numeric → `mean (SD)`, tested with `t.test` (binary outcome) or `aov` (>2 levels).",
    "- Non-normal numeric → `median (Q1, Q3)`, tested with `wilcox.test` or `kruskal.test`.",
    "- Categorical → `n (%)`, tested with `chisq.test`, falling back to `fisher.test` if expected counts < 5.",
))
cells.append(code(
    "n_out <- nlevels(df[[outcome]])",
    "",
    "stat_list <- setNames(",
    "  lapply(num_vars, function(v) if (is_normal(df[[v]])) \"{mean} ({sd})\" else \"{median} ({p25}, {p75})\"),",
    "  num_vars",
    ")",
    "",
    "# Named list of strings — works across gtsummary versions",
    "test_list <- list()",
    "for (v in num_vars) {",
    "  test_list[[v]] <- if (is_normal(df[[v]])) {",
    "    if (n_out == 2) \"t.test\" else \"aov\"",
    "  } else {",
    "    if (n_out == 2) \"wilcox.test\" else \"kruskal.test\"",
    "  }",
    "}",
    "for (v in cat_vars) {",
    "  tab <- table(df[[v]], df[[outcome]], useNA = \"ifany\")",
    "  expected_low <- tryCatch(",
    "    any(stats::chisq.test(tab)$expected < 5, na.rm = TRUE),",
    "    error = function(e) TRUE, warning = function(w) TRUE",
    "  )",
    "  test_list[[v]] <- if (isTRUE(expected_low)) \"fisher.test\" else \"chisq.test\"",
    "}",
    "",
    "bivariate_tbl <- df %>%",
    "  tbl_summary(",
    "    by = all_of(outcome),",
    "    statistic = stat_list,",
    "    missing = \"ifany\",",
    "    missing_text = \"Missing\"",
    "  ) %>%",
    "  add_overall() %>%",
    "  add_p(test = test_list) %>%",
    "  bold_labels()",
    "",
    "bivariate_tbl",
))
cells.append(code(
    "bivariate_tbl %>% as_gt() %>% gt::gtsave(table_path)",
    "cat(\"Saved table →\", table_path, \"\\n\")",
))

# ---- 8. Bivariate plots ------------------------------------------------
cells.append(md("## 7. Bivariate plots",
                "",
                "Numeric vs. outcome: violin + boxplot + jittered points. Categorical vs. outcome: stacked proportion bar."))
cells.append(code(
    "for (v in num_vars) {",
    "  p <- ggplot(df, aes(x = .data[[outcome]], y = .data[[v]], fill = .data[[outcome]])) +",
    "    geom_violin(alpha = 0.5, trim = FALSE) +",
    "    geom_boxplot(width = 0.15, alpha = 0.8, outlier.shape = NA) +",
    "    geom_jitter(width = 0.2, alpha = 0.3, size = 0.8) +",
    "    scale_fill_brewer(palette = \"Set2\") +",
    "    theme_minimal() +",
    "    labs(title = paste(\"Distribution of\", v, \"by\", outcome),",
    "         x = outcome, y = v)",
    "  print(p)",
    "  ggsave(file.path(plots_dir, paste0(\"biv_\", v, \"_vs_\", outcome, \".png\")), p,",
    "         width = 7, height = 5, dpi = 150)",
    "}",
))
cells.append(code(
    "for (v in cat_vars) {",
    "  p <- df %>%",
    "    count(.data[[outcome]], .data[[v]]) %>%",
    "    group_by(.data[[outcome]]) %>%",
    "    mutate(prop = n / sum(n)) %>%",
    "    ggplot(aes(x = .data[[outcome]], y = prop, fill = .data[[v]])) +",
    "    geom_col(position = \"fill\", color = \"white\") +",
    "    scale_fill_brewer(palette = \"Set2\") +",
    "    theme_minimal() +",
    "    labs(title = paste(\"Proportion of\", v, \"by\", outcome),",
    "         x = outcome, y = \"Proportion\", fill = v)",
    "  print(p)",
    "  ggsave(file.path(plots_dir, paste0(\"biv_\", v, \"_vs_\", outcome, \".png\")), p,",
    "         width = 7, height = 5, dpi = 150)",
    "}",
))

# ---- 9. Findings --------------------------------------------------------
cells.append(md(
    "## 8. Findings",
    "",
    "_Fill in once the cells above have been run — distribution shapes, missingness, top associations (low p-values), and caveats (small cells, heavy missingness, skew)._",
))

# ---- Notebook envelope --------------------------------------------------
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "name": "ir",
            "display_name": "R",
            "language": "R",
        },
        "language_info": {
            "name": "R",
            "codemirror_mode": "r",
            "file_extension": ".r",
            "mimetype": "text/x-r-source",
            "pygments_lexer": "r",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

Path(OUT_PATH).write_text(json.dumps(notebook, indent=1, ensure_ascii=False))
print(f"Wrote {OUT_PATH}")
