import json

cells = []

# 1. Title markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# EDA Report: NHANES (Adults 18–50)\\n",
        "\\n",
        "- **Variables analyzed**: Age, Gender, Race1, Weight, Height, Diabetes, BPSysAve, BPDiaAve\\n",
        "- **Outcome variable**: Diabetes\\n",
        "- **Filters applied**: Age 18–50, non-missing Diabetes\\n",
        "- **Generated by**: afeez\\n"
    ]
})

# 2. Setup
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Install & load required packages\\n",
        "pkgs \u003c- c(\"tidyverse\", \"gtsummary\", \"gt\", \"skimr\", \"knitr\")\\n",
        "install_if_missing \u003c- function(pkg) {\\n",
        "  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {\\n",
        "    install.packages(pkg)\\n",
        "    library(pkg, character.only = TRUE)\\n",
        "  }\\n",
        "}\\n",
        "invisible(sapply(pkgs, install_if_missing))\\n\\n",
        "library(tidyverse)\\n",
        "library(gtsummary)\\n",
        "library(gt)\\n",
        "library(skimr)\\n",
        "library(knitr)"
    ],
    "outputs": []
})

# 3. Data Load & Prep
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Load data\\n",
        "df \u003c- readr::read_csv(\"data/nhanes.csv\", na = c(\"\", \"NA\", \"N/A\", \".\"))\\n",
        "\\n",
        "# Select requested variables\\n",
        "sel_vars \u003c- c(\"Age\", \"Gender\", \"Race1\", \"Weight\", \"Height\", \"Diabetes\", \"BPSysAve\", \"BPDiaAve\")\\n",
        "df \u003c- df %\u003e% select(all_of(sel_vars))\\n",
        "\\n",
        "# Filter adults 18–50\\n",
        "df \u003c- df %\u003e% filter(Age \u003e= 18, Age \u003c= 50)\\n",
        "\\n",
        "# Remove rows with missing outcome\\n",
        "df \u003c- df %\u003e% filter(!is.na(Diabetes))\\n",
        "\\n",
        "# Factor categoricals\\n",
        "df$Diabetes \u003c- factor(df$Diabetes)\\n",
        "df$Gender \u003c- factor(df$Gender)\\n",
        "df$Race1 \u003c- factor(df$Race1)\\n",
        "\\n",
        "cat(\"Rows after filtering:\", nrow(df), \"\\n\")\\n",
        "cat(\"Outcome levels:\\n\")\\n",
        "print(table(df$Diabetes))"
    ],
    "outputs": []
})

# 4. Overview
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Dataset Overview\\n",
        "glimpse(df)\\n",
        "\\n",
        "# Missingness summary\\n",
        "df %\u003e%\\n",
        "  summarise(across(everything(), ~ sum(is.na(.)))) %\u003e%\\n",
        "  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_missing\") %\u003e%\\n",
        "  mutate(pct_missing = round(100 * n_missing / nrow(df), 1)) %\u003e%\\n",
        "  arrange(desc(n_missing))\\n",
        "\\n",
        "skim(df)"
    ],
    "outputs": []
})

# 5. Normality Assessment
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Normality Assessment (Shapiro-Wilk)\\n",
        "num_vars \u003c- names(df)[sapply(df, is.numeric)]\\n",
        "normality \u003c- tibble::tibble()\\n",
        "for (v in num_vars) {\\n",
        "  vals \u003c- na.omit(df[[v]])\\n",
        "  n \u003c- length(vals)\\n",
        "  if (n \u003e= 3 \u0026\u0026 n \u003c= 5000) {\\n",
        "    pval \u003c- stats::shapiro.test(vals)$p.value\\n",
        "    is_norm \u003c- pval \u003e 0.05\\n",
        "  } else {\\n",
        "    pval \u003c- NA\\n",
        "    is_norm \u003c- FALSE\\n",
        "  }\\n",
        "  normality \u003c- dplyr::bind_rows(normality, tibble::tibble(\\n",
        "    variable = v, n = n, shapiro_p = pval, is_normal = is_norm\\n",
        "  ))\\n",
        "}\\n",
        "print(normality)"
    ],
    "outputs": []
})

# 6. Univariate - numeric histograms
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Univariate Analysis\\n",
        "\\n",
        "### Numeric Variables"
    ]
})

for num_var in ["Weight", "Height", "Age", "BPSysAve", "BPDiaAve"]:
    code = (
        f"# Univariate: {num_var}\\n"
        f"ggplot(df, aes(x = {num_var})) +\\n"
        f'  geom_histogram(bins = 30, fill = "steelblue", color = "white", alpha = 0.8) +\\n'
        f"  theme_minimal() +\\n"
        f'  labs(title = "Distribution of {num_var}", x = "{num_var}", y = "Count")'
    )
    cells.append({"cell_type": "code", "execution_count": None, "metadata": {}, "source": [code], "outputs": []})

    code2 = (
        f"ggplot(df, aes(y = {num_var})) +\\n"
        f'  geom_boxplot(fill = "steelblue", alpha = 0.6, outlier.color = "red") +\\n'
        f"  theme_minimal() +\\n"
        f'  labs(title = "Boxplot of {num_var}", x = "", y = "{num_var}")'
    )
    cells.append({"cell_type": "code", "execution_count": None, "metadata": {}, "source": [code2], "outputs": []})

# 7. Univariate - categorical
cells.append({"cell_type": "markdown", "metadata": {}, "source": ["### Categorical Variables"] 
})

for cat_var in ["Gender", "Race1", "Diabetes"]:
    code = (
        f"# Univariate: {cat_var}\\n"
        f'df %\u003e%\\n'
        f'  count({cat_var}) %\u003e%\\n'
        f'  mutate(pct = scales::percent(n / sum(n), accuracy = 0.1)) %\u003e%\\n'
        f'  ggplot(aes(x = {cat_var}, y = n, fill = {cat_var})) +\\n'
        f'  geom_col(show.legend = FALSE) +\\n'
        f'  geom_text(aes(label = paste0(n, " (", pct, ")")), vjust = -0.3, size = 3) +\\n'
        f"  theme_minimal() +\\n"
        f'  labs(title = "Distribution of {cat_var}", x = "{cat_var}", y = "Count")'
    )
    cells.append({"cell_type": "code", "execution_count": None, "metadata": {}, "source": [code], "outputs": []})

# 8. Bivariate markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Bivariate Analysis by Diabetes\\n",
        "\\n",
        "- **Normal** numeric variables → mean (SD) with t-test (2 groups) or ANOVA (\u003e2 groups).\\n",
        "- **Non-normal** numeric variables → median (Q1–Q3) with Wilcoxon (2 groups) or Kruskal-Wallis (\u003e2 groups). \\(All numeric vars here are non-normal\\)\\n",
        "- Categorical variables → n (%) with chi-square or Fisher’s exact test."
    ]
})

# 9. Bivariate table
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Build normal-aware statistics and test lists\\n",
        "stat_list \u003c- list()\\n",
        "test_list \u003c- list()\\n",
        "n_out \u003c- nlevels(df$Diabetes)\\n",
        "for (v in names(df)[sapply(df, is.numeric)]) {\\n",
        "  vals \u003c- na.omit(df[[v]])\\n",
        "  n \u003c- length(vals)\\n",
        "  if (n \u003e= 3 \u0026\u0026 n \u003c= 5000) {\\n",
        "    is_norm \u003c- shapiro.test(vals)$p.value \u003e 0.05\\n",
        "  } else {\\n",
        "    is_norm \u003c- FALSE\\n",
        "  }\\n",
        "  stat_list[[v]] \u003c- if (is_norm) \"{mean} ({sd})\" else \"{median} ({p25}, {p75})\"\\n",
        "  if (is_norm) {\\n",
        "    test_list[[v]] \u003c- if (n_out == 2) \"t.test\" else \"aov\"\\n",
        "  } else {\\n",
        "    test_list[[v]] \u003c- if (n_out == 2) \"wilcox.test\" else \"kruskal.test\"\\n",
        "  }\\n",
        "}\\n",
        "for (v in names(df)[sapply(df, function(x) is.factor(x) || is.character(x))]) {\\n",
        "  tab \u003c- table(df[[v]], df$Diabetes, useNA = \"ifany\")\\n",
        "  if (any(chisq.test(tab)$expected \u003c 5, na.rm = TRUE)) {\\n",
        "    test_list[[v]] \u003c- \"fisher.test\"\\n",
        "  } else {\\n",
        "    test_list[[v]] \u003c- \"chisq.test\"\\n",
        "  }\\n",
        "}\\n",
        "\\n",
        "# Convert to gtsummary-accepted formula list\\n",
        "test_forms \u003c- purrr::imap(test_list, function(t, v) {\\n",
        '  as.formula(paste0(v, \" ~ \\\\\"\" , t, \"\\\\\"\"))\\n',
        "})\\n",
        "\\n",
        "bivariate_tbl \u003c- df %\u003e%\\n",
        "  tbl_summary(\\n",
        "    by = \"Diabetes\",\\n",
        "    statistic = stat_list,\\n",
        "    missing = \"ifany\",\\n",
        "    missing_text = \"Missing\"\\n",
        "  ) %\u003e%\\n",
        "  add_overall() %\u003e%\\n",
        "  add_p(test = test_forms) %\u003e%\\n",
        "  bold_labels()\\n",
        "\\n",
        "bivariate_tbl\\n",
        "\\n",
        "# Save table\\n",
        "bivariate_tbl %\u003e% as_gt() %\u003e% gt::gtsave(\"bivariate_table.html\")"
    ],
    "outputs": []
})

# 10. Bivariate plots
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": ["### Bivariate Plots"]
})

for v in ["Weight", "Height", "Age", "BPSysAve", "BPDiaAve"]:
    code = (
        f"# {v} vs Diabetes\\n"
        f"ggplot(df, aes(x = Diabetes, y = {v}, fill = Diabetes)) +\\n"
        f"  geom_violin(alpha = 0.5, trim = FALSE) +\\n"
        f"  geom_boxplot(width = 0.15, alpha = 0.8, outlier.shape = NA) +\\n"
        f"  geom_jitter(width = 0.2, alpha = 0.3, size = 0.8) +\\n"
        f"  scale_fill_brewer(palette = \"Set2\") +\\n"
        f"  theme_minimal() +\\n"
        f'  labs(title = "Distribution of {v} by Diabetes", x = "Diabetes", y = "{v}")'
    )
    cells.append({"cell_type": "code", "execution_count": None, "metadata": {}, "source": [code], "outputs": []})

for v in ["Gender", "Race1"]:
    code = (
        f"# {v} vs Diabetes\\n"
        f"df %\u003e%\\n"
        f"  dplyr::count(Diabetes, {v}) %\u003e%\\n"
        f"  dplyr::group_by(Diabetes) %\u003e%\\n"
        f"  dplyr::mutate(prop = n / sum(n)) %\u003e%\\n"
        f"  ggplot(aes(x = Diabetes, y = prop, fill = {v})) +\\n"
        f"  geom_col(position = \"fill\", color = \"white\") +\\n"
        f"  scale_fill_brewer(palette = \"Set2\") +\\n"
        f"  theme_minimal() +\\n"
        f'  labs(title = "Proportion of {v} by Diabetes", x = "Diabetes", y = "Proportion", fill = "{v}")'
    )
    cells.append({"cell_type": "code", "execution_count": None, "metadata": {}, "source": [code], "outputs": []})

# 11. Wrap-up
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Notes\\n",
        "\\n",
        "- Normality assessed with Shapiro-Wilk (n \u003c 3 or n \u003e 5000 auto-classified as non-normal).\\n",
        "- All numeric variables were treated as non-normal (median + Wilcoxon).\\n",
        "- Statistical tests selected parametrically vs. non-parametrically per Shapiro p-value.\\n",
        "- All visualisations use `theme_minimal()` for a clean aesthetic."
    ]
})

notebook = {
    "metadata": {
        "kernelspec": {
            "display_name": "R",
            "language": "R",
            "name": "ir"
        },
        "language_info": {
            "name": "R",
            "codemirror_mode": "r",
            "pygments_lexer": "r",
            "mimetype": "text/x-r-source",
            "file_extension": ".r"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5,
    "cells": cells
}

with open("nhanes_eda.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)

print("Notebook saved to nhanes_eda.ipynb")
